# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from .scrape import ScrapeResponse, ScrapeResponseInfo
from .scrape_js import (
    ScrapeJsResponse,
    ScrapeJsResponseInfo,
    ScrapeJsResponseInfoCatchedAjax,
    ScrapeJsV2Response,
    ScrapeJsV2ResponseInfo,
    ScrapeJsV2ResponseInfoCatchedAjax,
    ScrapeJsViewport,
)

__all__ = [
    "ScrapeJsResponse",
    "ScrapeJsResponseInfo",
    "ScrapeJsResponseInfoCatchedAjax",
    "ScrapeJsV2Response",
    "ScrapeJsV2ResponseInfo",
    "ScrapeJsV2ResponseInfoCatchedAjax",
    "ScrapeJsViewport",
    "ScrapeResponse",
    "ScrapeResponseInfo",
]
