# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, model_validator

from scrapeninja_web_scraping_api.client import NOT_GIVEN, NotGiven

from ..validation import validate_required


class ScrapeJsResponseInfoCatchedAjax(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    url: str | NotGiven = NOT_GIVEN
    """@example "https://example.com/api/data.json" """
    method: str | NotGiven = NOT_GIVEN
    """@example "GET" """
    headers: list[str] | NotGiven = NOT_GIVEN
    """
    Array of request headers

    @example ["content-type: xxx","header2: val2"]
    """
    body: str | NotGiven = NOT_GIVEN
    """@example "<html><body><h1>Hello World!</h1></body></html>" """
    body_iframe: str | NotGiven = Field(NOT_GIVEN, alias="bodyIframe")
    """
    If `dumpIframe` is activated, this property contains iframe HTML.

    @example "<html><body><h1>Iframe content</h1></body></html>"
    """
    status: int | NotGiven = NOT_GIVEN
    """@example 200"""
    response_headers: dict[str, Any] | NotGiven = Field(NOT_GIVEN, alias="responseHeaders")
    """
    Object with response headers

    @example {"content-type":"application/json"}
    """


class ScrapeJsResponseInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    status_code: int = Field(alias="statusCode")
    """@example 200"""
    final_url: str = Field(alias="finalUrl")
    """@example "https://example.com/url" """
    headers: list[str]
    """@example ["content-type: xxx","header2: val2"]"""
    catched_ajax: ScrapeJsResponseInfoCatchedAjax | NotGiven = Field(NOT_GIVEN, alias="catchedAjax")

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["statusCode", "finalUrl", "headers", "screenshot", "pageCookies"],
            {"statusCode": "status_code", "finalUrl": "final_url"},
        )
        return value


class ScrapeJsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    info: ScrapeJsResponseInfo | NotGiven = NOT_GIVEN
    body: str | NotGiven = NOT_GIVEN
    """
    HTML body of the rendered page.

    @example "<html><body><h1>Hello World!</h1></body></html>"
    """


class ScrapeJsV2ResponseInfoCatchedAjax(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    url: str | NotGiven = NOT_GIVEN
    """@example "https://example.com/api/data.json" """
    method: str | NotGiven = NOT_GIVEN
    """@example "GET" """
    headers: list[str] | NotGiven = NOT_GIVEN
    """
    Array of request headers

    @example ["content-type: xxx","header2: val2"]
    """
    body: str | NotGiven = NOT_GIVEN
    """@example "<html><body><h1>Hello World!</h1></body></html>" """
    body_iframe: str | NotGiven = Field(NOT_GIVEN, alias="bodyIframe")
    """
    If `dumpIframe` is activated, this property contains iframe HTML.

    @example "<html><body><h1>Iframe content</h1></body></html>"
    """
    status: int | NotGiven = NOT_GIVEN
    """@example 200"""
    response_headers: dict[str, Any] | NotGiven = Field(NOT_GIVEN, alias="responseHeaders")
    """
    Object with response headers

    @example {"content-type":"application/json"}
    """


class ScrapeJsV2ResponseInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    status_code: int = Field(alias="statusCode")
    """@example 200"""
    final_url: str = Field(alias="finalUrl")
    """@example "https://example.com/url" """
    headers: list[str]
    """@example ["content-type: xxx","header2: val2"]"""
    catched_ajax: ScrapeJsV2ResponseInfoCatchedAjax | NotGiven = Field(
        NOT_GIVEN, alias="catchedAjax"
    )

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["statusCode", "finalUrl", "headers", "screenshot", "pageCookies"],
            {"statusCode": "status_code", "finalUrl": "final_url"},
        )
        return value


class ScrapeJsV2Response(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    info: ScrapeJsV2ResponseInfo | NotGiven = NOT_GIVEN
    body: str | NotGiven = NOT_GIVEN
    """
    HTML body of the rendered page.

    @example "<html><body><h1>Hello World!</h1></body></html>"
    """


class ScrapeJsViewport(BaseModel):
    """Advanced. Set custom viewport size. By default, viewport size is 1920x1080."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    width: int | NotGiven = NOT_GIVEN
    """@example 1920"""
    height: int | NotGiven = NOT_GIVEN
    """@example 1080"""
    device_scale_factor: int | NotGiven = Field(NOT_GIVEN, alias="deviceScaleFactor")
    """@example 3"""
    has_touch: bool | NotGiven = Field(NOT_GIVEN, alias="hasTouch")
    """@example false"""
    is_mobile: bool | NotGiven = Field(NOT_GIVEN, alias="isMobile")
    """@example false"""
    is_landscape: bool | NotGiven = Field(NOT_GIVEN, alias="isLandscape")
    """@example false"""
