# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import fields, is_dataclass
from typing import Any, cast

from .errors import SdkValidationError
from .types import ScrapeJsResponse, ScrapeJsV2Response, ScrapeJsViewport, ScrapeResponse
from .wire import to_wire

MODEL_CONSTRUCTION_STYLE = "pydantic"

_SCHEMAS: dict[str, Any] = {
    "ScrapeResponse": {
        "type": "object",
        "properties": {
            "info": {
                "python": "info",
                "type": "object",
                "required": ["statusCode", "finalUrl", "headers"],
                "properties": {
                    "statusCode": {"python": "status_code", "type": "integer"},
                    "finalUrl": {"python": "final_url", "type": "string"},
                    "headers": {"python": "headers", "type": "array", "items": {"type": "string"}},
                },
            },
            "body": {"python": "body", "type": "string", "required": ["body"]},
        },
    },
    "ScrapeJsResponse": {
        "type": "object",
        "properties": {
            "info": {
                "python": "info",
                "type": "object",
                "required": ["statusCode", "finalUrl", "headers", "screenshot", "pageCookies"],
                "properties": {
                    "statusCode": {"python": "status_code", "type": "integer"},
                    "finalUrl": {"python": "final_url", "type": "string"},
                    "catchedAjax": {
                        "python": "catched_ajax",
                        "type": "object",
                        "properties": {
                            "url": {"python": "url", "type": "string"},
                            "method": {"python": "method", "type": "string"},
                            "headers": {
                                "python": "headers",
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "body": {"python": "body", "type": "string"},
                            "bodyIframe": {"python": "body_iframe", "type": "string"},
                            "status": {"python": "status", "type": "integer"},
                            "responseHeaders": {"python": "response_headers", "type": "object"},
                        },
                    },
                    "headers": {"python": "headers", "type": "array", "items": {"type": "string"}},
                },
            },
            "body": {"python": "body", "type": "string", "required": ["body"]},
        },
    },
    "ScrapeJsV2Response": {
        "type": "object",
        "properties": {
            "info": {
                "python": "info",
                "type": "object",
                "required": ["statusCode", "finalUrl", "headers", "screenshot", "pageCookies"],
                "properties": {
                    "statusCode": {"python": "status_code", "type": "integer"},
                    "finalUrl": {"python": "final_url", "type": "string"},
                    "catchedAjax": {
                        "python": "catched_ajax",
                        "type": "object",
                        "properties": {
                            "url": {"python": "url", "type": "string"},
                            "method": {"python": "method", "type": "string"},
                            "headers": {
                                "python": "headers",
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "body": {"python": "body", "type": "string"},
                            "bodyIframe": {"python": "body_iframe", "type": "string"},
                            "status": {"python": "status", "type": "integer"},
                            "responseHeaders": {"python": "response_headers", "type": "object"},
                        },
                    },
                    "headers": {"python": "headers", "type": "array", "items": {"type": "string"}},
                },
            },
            "body": {"python": "body", "type": "string", "required": ["body"]},
        },
    },
    "ScrapeJsViewport": {
        "type": "object",
        "properties": {
            "width": {"python": "width", "type": "integer"},
            "height": {"python": "height", "type": "integer"},
            "deviceScaleFactor": {"python": "device_scale_factor", "type": "integer"},
            "hasTouch": {"python": "has_touch", "type": "boolean"},
            "isMobile": {"python": "is_mobile", "type": "boolean"},
            "isLandscape": {"python": "is_landscape", "type": "boolean"},
        },
    },
}
_MODEL_TYPES: dict[str, type[Any]] = {
    "ScrapeResponse": ScrapeResponse,
    "ScrapeJsResponse": ScrapeJsResponse,
    "ScrapeJsV2Response": ScrapeJsV2Response,
    "ScrapeJsViewport": ScrapeJsViewport,
}
# Values that can never hold a nested model, so they need no cycle bookkeeping.
_SCALARS = (str, bytes, bool, int, float)


def _as_mapping(value: object) -> Mapping[str, object]:
    if isinstance(value, Mapping):
        return value
    if is_dataclass(value) and not isinstance(value, type):
        return {field.name: getattr(value, field.name) for field in fields(value)}
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return model_dump(by_alias=True, exclude_unset=True)
    raise TypeError("model construction values must be mappings or model instances")


def _field_value(value: object, wire_name: str, python_name: str) -> tuple[bool, object]:
    mapping = _as_mapping(value)
    if python_name in mapping:
        return True, mapping[python_name]
    if wire_name in mapping:
        return True, mapping[wire_name]
    return False, None


def _property_name(wire_name: str, schema: Mapping[str, Any]) -> str:
    return str(schema.get("python", wire_name))


def _child_field(field: str, child: str) -> str:
    return f"{field}.{child}" if field else child


def _resolve(schema: Mapping[str, Any]) -> tuple[str | None, Mapping[str, Any]]:
    """Follows a reference chain to the named schema it points at."""
    name: str | None = None
    visited: set[str] = set()
    reference = schema.get("ref")
    while isinstance(reference, str) and reference not in visited:
        visited.add(reference)
        name = reference
        target = _SCHEMAS.get(reference)
        schema = target if isinstance(target, Mapping) else {}
        reference = schema.get("ref")
    return name, schema


def _select_member(
    value: object,
    members: list[Any],
    field: str,
    active: set[tuple[int, int]],
) -> Mapping[str, Any] | None:
    """Returns the first union member the value satisfies, or raises its error."""
    rejection: SdkValidationError | None = None
    for member in members:
        if not isinstance(member, Mapping):
            continue
        try:
            _validate_node(value, member, field, active)
        except SdkValidationError as error:
            rejection = rejection or error
            continue
        return member
    if rejection is not None:
        raise rejection
    return None


def _validate_node(
    value: object,
    schema: Mapping[str, Any],
    field: str,
    active: set[tuple[int, int]],
) -> None:
    _name, resolved = _resolve(schema)
    if value is None:
        return

    # Recursive schemas describe finite values, so every node is validated. Only
    # a value that contains itself repeats a (value, schema) pair, and that can
    # never be constructed into a model.
    if not isinstance(value, _SCALARS):
        visit = (id(value), id(resolved))
        if visit in active:
            raise SdkValidationError(
                field,
                "recursion",
                f"Validation failed for '{field}': model value contains itself",
            )
        active = {*active, visit}

    for member in resolved.get("allOf", ()):
        if isinstance(member, Mapping):
            _validate_node(value, member, field, active)

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        _select_member(value, members, field, active)
        return

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        required = resolved.get("required", ())
        for wire_name in required if isinstance(required, list) else ():
            property_schema = properties.get(wire_name)
            python_name = (
                _property_name(wire_name, property_schema)
                if isinstance(property_schema, Mapping)
                else wire_name
            )
            present, property_value = _field_value(value, wire_name, python_name)
            if (
                not present
                or property_value is None
                and not (
                    isinstance(property_schema, Mapping) and property_schema.get("nullable") is True
                )
            ):
                raise SdkValidationError(
                    _child_field(field, wire_name),
                    "required",
                    f"Missing required property '{wire_name}'",
                )

        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            present, property_value = _field_value(
                value, wire_name, _property_name(wire_name, property_schema)
            )
            if present:
                _validate_node(
                    property_value,
                    property_schema,
                    _child_field(field, wire_name),
                    active,
                )

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        known = {
            name
            for wire_name, property_schema in (properties or {}).items()
            if isinstance(property_schema, Mapping)
            for name in (wire_name, _property_name(wire_name, property_schema))
        }
        for key, property_value in value.items():
            if key not in known:
                _validate_node(property_value, additional, _child_field(field, key), active)

    items = resolved.get("items")
    if isinstance(value, (list, tuple)) and isinstance(items, Mapping):
        for index, item in enumerate(value):
            _validate_node(item, items, _child_field(field, str(index)), active)


def _build(type_name: str | None, values: dict[str, object]) -> object:
    model_type = _MODEL_TYPES.get(type_name) if type_name is not None else None
    if model_type is None or MODEL_CONSTRUCTION_STYLE == "typeddict":
        return values
    return model_type(**values)


def _hydrate(value: object, schema: Mapping[str, Any], field: str) -> object:
    """Builds the public value for one schema node, constructing nested models."""
    name, resolved = _resolve(schema)
    if value is None:
        return None

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        member = _select_member(value, members, field, set())
        return value if member is None else _hydrate(value, member, field)

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        values: dict[str, object] = {}
        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            python_name = _property_name(wire_name, property_schema)
            present, property_value = _field_value(value, wire_name, python_name)
            if present:
                values[python_name] = _hydrate(
                    property_value, property_schema, _child_field(field, wire_name)
                )
        return _build(name, values)

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        return {
            key: _hydrate(item, additional, _child_field(field, key)) for key, item in value.items()
        }

    items = resolved.get("items")
    if isinstance(items, Mapping) and isinstance(value, (list, tuple)):
        return [
            _hydrate(item, items, _child_field(field, str(index)))
            for index, item in enumerate(value)
        ]

    return value


def _construct_model(value: object, type_name: str) -> object:
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    _validate_node(value, {"ref": type_name}, "", set())
    if MODEL_CONSTRUCTION_STYLE == "pydantic":
        # Pydantic owns nested construction: its declared field types already
        # describe every referenced model. The wire remapper first restores the
        # spec spelling that the generated aliases and validators expect.
        return _MODEL_TYPES[type_name].model_validate(to_wire(value, type_name))
    return _hydrate(value, {"ref": type_name}, "")


def create_scrape_response(value: Mapping[str, object]) -> ScrapeResponse:
    """Construct one ScrapeResponse after applying its schema constraints."""
    return cast(ScrapeResponse, _construct_model(value, "ScrapeResponse"))


def create_scrape_js_response(value: Mapping[str, object]) -> ScrapeJsResponse:
    """Construct one ScrapeJsResponse after applying its schema constraints."""
    return cast(ScrapeJsResponse, _construct_model(value, "ScrapeJsResponse"))


def create_scrape_js_v2_response(value: Mapping[str, object]) -> ScrapeJsV2Response:
    """Construct one ScrapeJsV2Response after applying its schema constraints."""
    return cast(ScrapeJsV2Response, _construct_model(value, "ScrapeJsV2Response"))


def create_scrape_js_viewport(value: Mapping[str, object]) -> ScrapeJsViewport:
    """Construct one ScrapeJsViewport after applying its schema constraints."""
    return cast(ScrapeJsViewport, _construct_model(value, "ScrapeJsViewport"))


def serialize_model(value: object, type_name: str) -> object:
    """Serialize a constructed model using the generated wire-name registry."""
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    return to_wire(value, type_name)


def deserialize_model(value: object, type_name: str) -> object:
    """Validate and construct a model from its JSON-shaped representation."""
    return _construct_model(value, type_name)


__all__ = [
    "MODEL_CONSTRUCTION_STYLE",
    "create_scrape_js_response",
    "create_scrape_js_v2_response",
    "create_scrape_js_viewport",
    "create_scrape_response",
    "deserialize_model",
    "serialize_model",
]
