# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.scrape_js import scrape_js, scrape_js_sync, scrape_js_v2, scrape_js_v2_sync


class _ScrapeJsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.scrape_js = partial(scrape_js, config)
        self.scrape_js.__doc__ = scrape_js.__doc__
        self.scrape_js_sync = partial(scrape_js_sync, config)
        self.scrape_js_sync.__doc__ = scrape_js_sync.__doc__
        self.v2 = partial(scrape_js_v2, config)
        self.v2.__doc__ = scrape_js_v2.__doc__
        self.v2_sync = partial(scrape_js_v2_sync, config)
        self.v2_sync.__doc__ = scrape_js_v2_sync.__doc__
