# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.scrape import scrape, scrape_sync


class _ScrapeNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.scrape = partial(scrape, config)
        self.scrape.__doc__ = scrape.__doc__
        self.scrape_sync = partial(scrape_sync, config)
        self.scrape_sync.__doc__ = scrape_sync.__doc__
