# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import sdk.types as _response_types
from sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from sdk.types import ScrapeJsResponse, ScrapeJsV2Response, ScrapeJsViewport
from sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def scrape_js(
    _client_config: ClientConfig,
    url: str,
    wait_for_selector: str | NotGiven = NOT_GIVEN,
    post_wait_time: int | NotGiven = NOT_GIVEN,
    dump_iframe: str | NotGiven = NOT_GIVEN,
    wait_for_selector_iframe: str | NotGiven = NOT_GIVEN,
    extractor_target_iframe: bool | NotGiven = NOT_GIVEN,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    block_images: bool | NotGiven = NOT_GIVEN,
    block_media: bool | NotGiven = NOT_GIVEN,
    screenshot: bool | NotGiven = NOT_GIVEN,
    catch_ajax_headers_url_mask: str | NotGiven = NOT_GIVEN,
    viewport: ScrapeJsViewport | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeJsResponse:
    """Scrapes a URL with a real Chrome browser engine to render JavaScript-dependent
    pages. Use this endpoint when `/scrape` does not retrieve the required page content;
    set `waitForSelector` or `postWaitTime` when you need to control when page loading
    is considered complete. The response includes the rendered HTML and browser
    metadata.

    Launches real Chrome browser engine, use only when /scrape endpoint features are not
    enough.

    Args:
        url: URL to scrape
        wait_for_selector: CSS selector to wait to appear in DOM tree before page is considered as loaded.
        post_wait_time: Wait for specified amount of seconds after page load (from 1 to 12s). Use this
            only if ScrapeNinja failed to wait for required page elements automatically.
        dump_iframe: If some particular iframe needs to be dumped, specify its `name` HTML value in
            this argument. The ScrapeNinja JS renderer will wait for <iframe
            name="icims_content_iframe"> to appear in DOM, then use `waitForSelectorIframe`
            CSS selector to wait for iframe DOM elements to appear inside.
        wait_for_selector_iframe: If `dumpIframe` is activated, this property allows to wait for CSS selector
            inside this iframe.
        extractor_target_iframe: If `dumpIframe` is activated, this property allows to run JS extractor function
            against iframe HTML instead of running it against base body. This is only useful
            if `dumpIframe` is activated.
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        block_images: Block images from loading. This will speed up page loading and reduce bandwidth
            usage.
        block_media: Block (CSS, fonts) from loading. This will speed up page loading and reduce
            bandwidth usage.
        screenshot: Take a screenshot of the page. Pass "false" to increase the speed of the
            request.
        catch_ajax_headers_url_mask: Useful to dump some XHR response. Pass URL mask here. For example, if you need
            to catch all requests to https://example.com/api/data.json, pass "api/data.json"
            here. In response, you will get new property `.info.catchedAjax` with the XHR
            response data - { url, method, headers[], body , status, responseHeaders{} }
        viewport: Advanced. Set custom viewport size. By default, viewport size is 1920x1080.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = await sdk_request(
        "POST",
        "/scrape-js",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "waitForSelector": (
                    NOT_GIVEN
                    if wait_for_selector is NOT_GIVEN
                    else to_wire(wait_for_selector, "str")
                ),
                "postWaitTime": (
                    NOT_GIVEN if post_wait_time is NOT_GIVEN else to_wire(post_wait_time, "int")
                ),
                "dumpIframe": (
                    NOT_GIVEN if dump_iframe is NOT_GIVEN else to_wire(dump_iframe, "str")
                ),
                "waitForSelectorIframe": (
                    NOT_GIVEN
                    if wait_for_selector_iframe is NOT_GIVEN
                    else to_wire(wait_for_selector_iframe, "str")
                ),
                "extractorTargetIframe": (
                    NOT_GIVEN
                    if extractor_target_iframe is NOT_GIVEN
                    else to_wire(extractor_target_iframe, "bool")
                ),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "blockImages": (
                    NOT_GIVEN if block_images is NOT_GIVEN else to_wire(block_images, "bool")
                ),
                "blockMedia": (
                    NOT_GIVEN if block_media is NOT_GIVEN else to_wire(block_media, "bool")
                ),
                "screenshot": (
                    NOT_GIVEN if screenshot is NOT_GIVEN else to_wire(screenshot, "bool")
                ),
                "catchAjaxHeadersUrlMask": (
                    NOT_GIVEN
                    if catch_ajax_headers_url_mask is NOT_GIVEN
                    else to_wire(catch_ajax_headers_url_mask, "str")
                ),
                "viewport": (
                    NOT_GIVEN if viewport is NOT_GIVEN else to_wire(viewport, "ScrapeJsViewport")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape_js",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeJsResponse"), ScrapeJsResponse
    )


def scrape_js_sync(
    _client_config: ClientConfig,
    url: str,
    wait_for_selector: str | NotGiven = NOT_GIVEN,
    post_wait_time: int | NotGiven = NOT_GIVEN,
    dump_iframe: str | NotGiven = NOT_GIVEN,
    wait_for_selector_iframe: str | NotGiven = NOT_GIVEN,
    extractor_target_iframe: bool | NotGiven = NOT_GIVEN,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    block_images: bool | NotGiven = NOT_GIVEN,
    block_media: bool | NotGiven = NOT_GIVEN,
    screenshot: bool | NotGiven = NOT_GIVEN,
    catch_ajax_headers_url_mask: str | NotGiven = NOT_GIVEN,
    viewport: ScrapeJsViewport | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeJsResponse:
    """Scrapes a URL with a real Chrome browser engine to render JavaScript-dependent
    pages. Use this endpoint when `/scrape` does not retrieve the required page content;
    set `waitForSelector` or `postWaitTime` when you need to control when page loading
    is considered complete. The response includes the rendered HTML and browser
    metadata.

    Launches real Chrome browser engine, use only when /scrape endpoint features are not
    enough.

    Args:
        url: URL to scrape
        wait_for_selector: CSS selector to wait to appear in DOM tree before page is considered as loaded.
        post_wait_time: Wait for specified amount of seconds after page load (from 1 to 12s). Use this
            only if ScrapeNinja failed to wait for required page elements automatically.
        dump_iframe: If some particular iframe needs to be dumped, specify its `name` HTML value in
            this argument. The ScrapeNinja JS renderer will wait for <iframe
            name="icims_content_iframe"> to appear in DOM, then use `waitForSelectorIframe`
            CSS selector to wait for iframe DOM elements to appear inside.
        wait_for_selector_iframe: If `dumpIframe` is activated, this property allows to wait for CSS selector
            inside this iframe.
        extractor_target_iframe: If `dumpIframe` is activated, this property allows to run JS extractor function
            against iframe HTML instead of running it against base body. This is only useful
            if `dumpIframe` is activated.
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        block_images: Block images from loading. This will speed up page loading and reduce bandwidth
            usage.
        block_media: Block (CSS, fonts) from loading. This will speed up page loading and reduce
            bandwidth usage.
        screenshot: Take a screenshot of the page. Pass "false" to increase the speed of the
            request.
        catch_ajax_headers_url_mask: Useful to dump some XHR response. Pass URL mask here. For example, if you need
            to catch all requests to https://example.com/api/data.json, pass "api/data.json"
            here. In response, you will get new property `.info.catchedAjax` with the XHR
            response data - { url, method, headers[], body , status, responseHeaders{} }
        viewport: Advanced. Set custom viewport size. By default, viewport size is 1920x1080.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = sdk_request_sync(
        "POST",
        "/scrape-js",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "waitForSelector": (
                    NOT_GIVEN
                    if wait_for_selector is NOT_GIVEN
                    else to_wire(wait_for_selector, "str")
                ),
                "postWaitTime": (
                    NOT_GIVEN if post_wait_time is NOT_GIVEN else to_wire(post_wait_time, "int")
                ),
                "dumpIframe": (
                    NOT_GIVEN if dump_iframe is NOT_GIVEN else to_wire(dump_iframe, "str")
                ),
                "waitForSelectorIframe": (
                    NOT_GIVEN
                    if wait_for_selector_iframe is NOT_GIVEN
                    else to_wire(wait_for_selector_iframe, "str")
                ),
                "extractorTargetIframe": (
                    NOT_GIVEN
                    if extractor_target_iframe is NOT_GIVEN
                    else to_wire(extractor_target_iframe, "bool")
                ),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "blockImages": (
                    NOT_GIVEN if block_images is NOT_GIVEN else to_wire(block_images, "bool")
                ),
                "blockMedia": (
                    NOT_GIVEN if block_media is NOT_GIVEN else to_wire(block_media, "bool")
                ),
                "screenshot": (
                    NOT_GIVEN if screenshot is NOT_GIVEN else to_wire(screenshot, "bool")
                ),
                "catchAjaxHeadersUrlMask": (
                    NOT_GIVEN
                    if catch_ajax_headers_url_mask is NOT_GIVEN
                    else to_wire(catch_ajax_headers_url_mask, "str")
                ),
                "viewport": (
                    NOT_GIVEN if viewport is NOT_GIVEN else to_wire(viewport, "ScrapeJsViewport")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape_js",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeJsResponse"), ScrapeJsResponse
    )


async def scrape_js_v2(
    _client_config: ClientConfig,
    url: str,
    wait_for_selector: str | NotGiven = NOT_GIVEN,
    post_wait_time: int | NotGiven = NOT_GIVEN,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    block_images: bool | NotGiven = NOT_GIVEN,
    block_media: bool | NotGiven = NOT_GIVEN,
    screenshot: bool | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeJsV2Response:
    """Scrapes a URL with the newer real Chrome browser engine to render
    JavaScript-dependent pages. Use this endpoint when browser rendering is required,
    including for sites protected by services such as Cloudflare, Datadome, Kasada, or
    PerimeterX. Access is available only through APIRoad.

    Launches real Chrome browser engine, better success rate for websites protected by
    Cloudflare, Datadome, Kasada, PermimeterX. ATTENTION: Only available via APIRoad!

    Args:
        url: URL to scrape
        wait_for_selector: CSS selector to wait to appear in DOM tree before page is considered as loaded.
        post_wait_time: Wait for specified amount of seconds after page load (from 1 to 12s). Use this
            only if ScrapeNinja failed to wait for required page elements automatically.
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        block_images: Block images from loading. This will speed up page loading and reduce bandwidth
            usage.
        block_media: Block (CSS, fonts) from loading. This will speed up page loading and reduce
            bandwidth usage.
        screenshot: Take a screenshot of the page. Pass "false" to increase the speed of the
            request.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = await sdk_request(
        "POST",
        "/v2/scrape-js",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "waitForSelector": (
                    NOT_GIVEN
                    if wait_for_selector is NOT_GIVEN
                    else to_wire(wait_for_selector, "str")
                ),
                "postWaitTime": (
                    NOT_GIVEN if post_wait_time is NOT_GIVEN else to_wire(post_wait_time, "int")
                ),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "blockImages": (
                    NOT_GIVEN if block_images is NOT_GIVEN else to_wire(block_images, "bool")
                ),
                "blockMedia": (
                    NOT_GIVEN if block_media is NOT_GIVEN else to_wire(block_media, "bool")
                ),
                "screenshot": (
                    NOT_GIVEN if screenshot is NOT_GIVEN else to_wire(screenshot, "bool")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape_js_v2",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeJsV2Response"), ScrapeJsV2Response
    )


def scrape_js_v2_sync(
    _client_config: ClientConfig,
    url: str,
    wait_for_selector: str | NotGiven = NOT_GIVEN,
    post_wait_time: int | NotGiven = NOT_GIVEN,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    block_images: bool | NotGiven = NOT_GIVEN,
    block_media: bool | NotGiven = NOT_GIVEN,
    screenshot: bool | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeJsV2Response:
    """Scrapes a URL with the newer real Chrome browser engine to render
    JavaScript-dependent pages. Use this endpoint when browser rendering is required,
    including for sites protected by services such as Cloudflare, Datadome, Kasada, or
    PerimeterX. Access is available only through APIRoad.

    Launches real Chrome browser engine, better success rate for websites protected by
    Cloudflare, Datadome, Kasada, PermimeterX. ATTENTION: Only available via APIRoad!

    Args:
        url: URL to scrape
        wait_for_selector: CSS selector to wait to appear in DOM tree before page is considered as loaded.
        post_wait_time: Wait for specified amount of seconds after page load (from 1 to 12s). Use this
            only if ScrapeNinja failed to wait for required page elements automatically.
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        block_images: Block images from loading. This will speed up page loading and reduce bandwidth
            usage.
        block_media: Block (CSS, fonts) from loading. This will speed up page loading and reduce
            bandwidth usage.
        screenshot: Take a screenshot of the page. Pass "false" to increase the speed of the
            request.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = sdk_request_sync(
        "POST",
        "/v2/scrape-js",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "waitForSelector": (
                    NOT_GIVEN
                    if wait_for_selector is NOT_GIVEN
                    else to_wire(wait_for_selector, "str")
                ),
                "postWaitTime": (
                    NOT_GIVEN if post_wait_time is NOT_GIVEN else to_wire(post_wait_time, "int")
                ),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "blockImages": (
                    NOT_GIVEN if block_images is NOT_GIVEN else to_wire(block_images, "bool")
                ),
                "blockMedia": (
                    NOT_GIVEN if block_media is NOT_GIVEN else to_wire(block_media, "bool")
                ),
                "screenshot": (
                    NOT_GIVEN if screenshot is NOT_GIVEN else to_wire(screenshot, "bool")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape_js_v2",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeJsV2Response"), ScrapeJsV2Response
    )


__all__ = [
    "scrape_js",
    "scrape_js_sync",
    "scrape_js_v2",
    "scrape_js_v2_sync",
]
