# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import sdk.types as _response_types
from sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from sdk.types import ScrapeResponse
from sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def scrape(
    _client_config: ClientConfig,
    url: str,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    follow_redirects: int | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeResponse:
    """Scrapes a URL using Chrome browser TLS fingerprinting without executing JavaScript.
    Use this endpoint for pages that do not require client-side rendering, and set
    `headers`, `geo`, or `proxy` to customize the request. The response includes the
    HTML body and request metadata.

    Use high-performance web scraping endpoint with Chrome browser TLS fingerprint, but
    without JavaScript execution and real browser overhead.

    Args:
        url: URL to scrape
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        follow_redirects: Follow redirects.
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = await sdk_request(
        "POST",
        "/scrape",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "followRedirects": (
                    NOT_GIVEN if follow_redirects is NOT_GIVEN else to_wire(follow_redirects, "int")
                ),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeResponse"), ScrapeResponse
    )


def scrape_sync(
    _client_config: ClientConfig,
    url: str,
    headers: list[str] | NotGiven = NOT_GIVEN,
    retry_num: int | NotGiven = NOT_GIVEN,
    geo: str | NotGiven = NOT_GIVEN,
    proxy: str | NotGiven = NOT_GIVEN,
    follow_redirects: int | NotGiven = NOT_GIVEN,
    timeout: int | NotGiven = NOT_GIVEN,
    text_not_expected: list[str] | NotGiven = NOT_GIVEN,
    status_not_expected: list[int] | NotGiven = NOT_GIVEN,
    extractor: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ScrapeResponse:
    """Scrapes a URL using Chrome browser TLS fingerprinting without executing JavaScript.
    Use this endpoint for pages that do not require client-side rendering, and set
    `headers`, `geo`, or `proxy` to customize the request. The response includes the
    HTML body and request metadata.

    Use high-performance web scraping endpoint with Chrome browser TLS fingerprint, but
    without JavaScript execution and real browser overhead.

    Args:
        url: URL to scrape
        headers: Custom headers to send with the request. By default, regular Chrome browser
            headers are sent to the target URL.
        retry_num: Amount of attempts.
        geo: Geo location for basic proxy pools (you can purchase premium ScrapeNinja proxies
            for wider country selection and higher proxy quality). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        proxy: Premium or your own proxy URL (overrides `geo` field). [Read more about
            ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
        follow_redirects: Follow redirects.
        timeout: Timeout per attempt, in seconds. Each retry will take [timeout] number of
            seconds.
        text_not_expected: Text which will trigger a retry from another proxy address.
        status_not_expected: HTTP response statuses which will trigger a retry from another proxy address.
        extractor: Custom JS function to extract JSON values from scraped HTML. Write&test your own
            extractor on https://scrapeninja.net/cheerio-sandbox/
    """

    _resp = sdk_request_sync(
        "POST",
        "/scrape",
        json=omit_unset(
            {
                "url": (NOT_GIVEN if url is NOT_GIVEN else to_wire(url, "str")),
                "headers": (NOT_GIVEN if headers is NOT_GIVEN else to_wire(headers, "list[str]")),
                "retryNum": (NOT_GIVEN if retry_num is NOT_GIVEN else to_wire(retry_num, "int")),
                "geo": (NOT_GIVEN if geo is NOT_GIVEN else to_wire(geo, "str")),
                "proxy": (NOT_GIVEN if proxy is NOT_GIVEN else to_wire(proxy, "str")),
                "followRedirects": (
                    NOT_GIVEN if follow_redirects is NOT_GIVEN else to_wire(follow_redirects, "int")
                ),
                "timeout": (NOT_GIVEN if timeout is NOT_GIVEN else to_wire(timeout, "int")),
                "textNotExpected": (
                    NOT_GIVEN
                    if text_not_expected is NOT_GIVEN
                    else to_wire(text_not_expected, "list[str]")
                ),
                "statusNotExpected": (
                    NOT_GIVEN
                    if status_not_expected is NOT_GIVEN
                    else to_wire(status_not_expected, "list[int]")
                ),
                "extractor": (NOT_GIVEN if extractor is NOT_GIVEN else to_wire(extractor, "str")),
            }
        ),
        operation_id="scrape",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ScrapeResponse"), ScrapeResponse
    )


__all__ = [
    "scrape",
    "scrape_sync",
]
