# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_required


class ScrapeResponseInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    status_code: int = Field(alias="statusCode")
    """@example 200"""
    final_url: str = Field(alias="finalUrl")
    """@example "https://example.com/url" """
    headers: list[str]
    """@example ["content-type: xxx","header2: val2"]"""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["statusCode", "finalUrl", "headers"],
            {"statusCode": "status_code", "finalUrl": "final_url"},
        )
        return value


class ScrapeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    info: ScrapeResponseInfo | NotGiven = NOT_GIVEN
    body: str | NotGiven = NOT_GIVEN
    """
    HTML body of the rendered page.

    @example "<html><body><h1>Hello World!</h1></body></html>"
    """
