// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export interface ScrapeJsParams {
  url: string;
  waitForSelector?: string;
  postWaitTime?: number;
  dumpIframe?: string;
  waitForSelectorIframe?: string;
  extractorTargetIframe?: boolean;
  headers?: string[];
  retryNum?: number;
  geo?: string;
  proxy?: string;
  timeout?: number;
  textNotExpected?: string[];
  statusNotExpected?: number[];
  blockImages?: boolean;
  blockMedia?: boolean;
  screenshot?: boolean;
  catchAjaxHeadersUrlMask?: string;
  viewport?: {
    /**
     *
     * @example 1920
     */
    width?: number;
    /**
     *
     * @example 1080
     */
    height?: number;
    /**
     *
     * @example 3
     */
    deviceScaleFactor?: number;
    hasTouch?: boolean;
    isMobile?: boolean;
    isLandscape?: boolean;
  };
  extractor?: string;
}

/**
 * Scrapes a URL with a real Chrome browser engine to render JavaScript-dependent pages. Use this endpoint when `/scrape` does not retrieve the required page content; set `waitForSelector` or `postWaitTime` when you need to control when page loading is considered complete. The response includes the rendered HTML and browser metadata.
 *
 * Launches real Chrome browser engine, use only when /scrape endpoint features are not enough.
 *
 * @param url - URL to scrape
 * @param waitForSelector - CSS selector to wait to appear in DOM tree before
 *   page is considered as loaded.
 * @param postWaitTime - Wait for specified amount of seconds after page load
 *   (from 1 to 12s). Use this only if ScrapeNinja failed to wait for required page
 *   elements automatically.
 * @param dumpIframe - If some particular iframe needs to be dumped, specify its
 *   `name` HTML value in this argument. The ScrapeNinja JS renderer will wait for
 *   <iframe name="icims_content_iframe"> to appear in DOM, then use
 *   `waitForSelectorIframe` CSS selector to wait for iframe DOM elements to appear
 *   inside.
 * @param waitForSelectorIframe - If `dumpIframe` is activated, this property
 *   allows to wait for CSS selector inside this iframe.
 * @param extractorTargetIframe - If `dumpIframe` is activated, this property
 *   allows to run JS extractor function against iframe HTML instead of running it
 *   against base body. This is only useful if `dumpIframe` is activated.
 * @param headers - Custom headers to send with the request. By default, regular
 *   Chrome browser headers are sent to the target URL.
 * @param retryNum - Amount of attempts.
 * @param geo - Geo location for basic proxy pools (you can purchase premium
 *   ScrapeNinja proxies for wider country selection and higher proxy quality).
 *   [Read more about ScrapeNinja proxy
 *   setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param proxy - Premium or your own proxy URL (overrides `geo` field). [Read
 *   more about ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param timeout - Timeout per attempt, in seconds. Each retry will take
 *   [timeout] number of seconds.
 * @param textNotExpected - Text which will trigger a retry from another proxy
 *   address.
 * @param statusNotExpected - HTTP response statuses which will trigger a retry
 *   from another proxy address.
 * @param blockImages - Block images from loading. This will speed up page
 *   loading and reduce bandwidth usage.
 * @param blockMedia - Block (CSS, fonts) from loading. This will speed up page
 *   loading and reduce bandwidth usage.
 * @param screenshot - Take a screenshot of the page. Pass "false" to increase
 *   the speed of the request.
 * @param catchAjaxHeadersUrlMask - Useful to dump some XHR response. Pass URL
 *   mask here. For example, if you need to catch all requests to
 *   https://example.com/api/data.json, pass "api/data.json" here. In response, you
 *   will get new property `.info.catchedAjax` with the XHR response data - { url,
 *   method, headers[], body , status, responseHeaders{} }
 * @param viewport - Advanced. Set custom viewport size. By default, viewport
 *   size is 1920x1080.
 * @param extractor - Custom JS function to extract JSON values from scraped
 *   HTML. Write&test your own extractor on
 *   https://scrapeninja.net/cheerio-sandbox/
 */
export async function scrapeJs(
  config: ClientConfig,
  {
    url,
    waitForSelector,
    postWaitTime,
    dumpIframe,
    waitForSelectorIframe,
    extractorTargetIframe,
    headers,
    retryNum,
    geo,
    proxy,
    timeout,
    textNotExpected,
    statusNotExpected,
    blockImages,
    blockMedia,
    screenshot,
    catchAjaxHeadersUrlMask,
    viewport,
    extractor,
  }: ScrapeJsParams,
  requestOptions?: RequestOptions,
): Promise<{
  info?: {
    /**
     *
     * @example 200
     */
    statusCode: number;
    /**
     *
     * @example "https://example.com/url"
     */
    finalUrl: string;
    catchedAjax?: {
      /**
       *
       * @example "https://example.com/api/data.json"
       */
      url?: string;
      /**
       *
       * @example "GET"
       */
      method?: string;
      /**
       * Array of request headers

       * @example ["content-type: xxx","header2: val2"]
       */
      headers?: string[];
      /**
       *
       * @example "<html><body><h1>Hello World!</h1></body></html>"
       */
      body?: string;
      /**
       * If `dumpIframe` is activated, this property contains iframe HTML.

       * @example "<html><body><h1>Iframe content</h1></body></html>"
       */
      bodyIframe?: string;
      /**
       *
       * @example 200
       */
      status?: number;
      /**
       * Object with response headers

       * @example {"content-type":"application/json"}
       */
      responseHeaders?: { [key: string]: unknown };
    };
    /**
     *
     * @example ["content-type: xxx","header2: val2"]
     */
    headers: string[];
  };
  /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
  body?: string;
}> {
  const _resp = await sdkRequest<{
    info?: {
      /**
       *
       * @example 200
       */
      statusCode: number;
      /**
       *
       * @example "https://example.com/url"
       */
      finalUrl: string;
      catchedAjax?: {
        /**
         *
         * @example "https://example.com/api/data.json"
         */
        url?: string;
        /**
         *
         * @example "GET"
         */
        method?: string;
        /**
       * Array of request headers

       * @example ["content-type: xxx","header2: val2"]
       */
        headers?: string[];
        /**
         *
         * @example "<html><body><h1>Hello World!</h1></body></html>"
         */
        body?: string;
        /**
       * If `dumpIframe` is activated, this property contains iframe HTML.

       * @example "<html><body><h1>Iframe content</h1></body></html>"
       */
        bodyIframe?: string;
        /**
         *
         * @example 200
         */
        status?: number;
        /**
       * Object with response headers

       * @example {"content-type":"application/json"}
       */
        responseHeaders?: { [key: string]: unknown };
      };
      /**
       *
       * @example ["content-type: xxx","header2: val2"]
       */
      headers: string[];
    };
    /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
    body?: string;
  }>({
    method: "POST",
    path: `/scrape-js`,
    operationId: "scrapeJs",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      url,
      waitForSelector,
      postWaitTime,
      dumpIframe,
      waitForSelectorIframe,
      extractorTargetIframe,
      headers,
      retryNum,
      geo,
      proxy,
      timeout,
      textNotExpected,
      statusNotExpected,
      blockImages,
      blockMedia,
      screenshot,
      catchAjaxHeadersUrlMask,
      viewport,
      extractor,
    },
    config,
  });
  return _resp.data;
}

export interface ScrapeJsV2Params {
  url: string;
  waitForSelector?: string;
  postWaitTime?: number;
  headers?: string[];
  retryNum?: number;
  geo?: string;
  proxy?: string;
  timeout?: number;
  textNotExpected?: string[];
  statusNotExpected?: number[];
  blockImages?: boolean;
  blockMedia?: boolean;
  screenshot?: boolean;
  extractor?: string;
}

/**
 * Scrapes a URL with the newer real Chrome browser engine to render JavaScript-dependent pages. Use this endpoint when browser rendering is required, including for sites protected by services such as Cloudflare, Datadome, Kasada, or PerimeterX. Access is available only through APIRoad.
 *
 * Launches real Chrome browser engine, better success rate for websites protected by Cloudflare, Datadome, Kasada, PermimeterX. ATTENTION: Only available via APIRoad!
 *
 * @param url - URL to scrape
 * @param waitForSelector - CSS selector to wait to appear in DOM tree before
 *   page is considered as loaded.
 * @param postWaitTime - Wait for specified amount of seconds after page load
 *   (from 1 to 12s). Use this only if ScrapeNinja failed to wait for required page
 *   elements automatically.
 * @param headers - Custom headers to send with the request. By default, regular
 *   Chrome browser headers are sent to the target URL.
 * @param retryNum - Amount of attempts.
 * @param geo - Geo location for basic proxy pools (you can purchase premium
 *   ScrapeNinja proxies for wider country selection and higher proxy quality).
 *   [Read more about ScrapeNinja proxy
 *   setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param proxy - Premium or your own proxy URL (overrides `geo` field). [Read
 *   more about ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param timeout - Timeout per attempt, in seconds. Each retry will take
 *   [timeout] number of seconds.
 * @param textNotExpected - Text which will trigger a retry from another proxy
 *   address.
 * @param statusNotExpected - HTTP response statuses which will trigger a retry
 *   from another proxy address.
 * @param blockImages - Block images from loading. This will speed up page
 *   loading and reduce bandwidth usage.
 * @param blockMedia - Block (CSS, fonts) from loading. This will speed up page
 *   loading and reduce bandwidth usage.
 * @param screenshot - Take a screenshot of the page. Pass "false" to increase
 *   the speed of the request.
 * @param extractor - Custom JS function to extract JSON values from scraped
 *   HTML. Write&test your own extractor on
 *   https://scrapeninja.net/cheerio-sandbox/
 */
export async function scrapeJsV2(
  config: ClientConfig,
  {
    url,
    waitForSelector,
    postWaitTime,
    headers,
    retryNum,
    geo,
    proxy,
    timeout,
    textNotExpected,
    statusNotExpected,
    blockImages,
    blockMedia,
    screenshot,
    extractor,
  }: ScrapeJsV2Params,
  requestOptions?: RequestOptions,
): Promise<{
  info?: {
    /**
     *
     * @example 200
     */
    statusCode: number;
    /**
     *
     * @example "https://example.com/url"
     */
    finalUrl: string;
    catchedAjax?: {
      /**
       *
       * @example "https://example.com/api/data.json"
       */
      url?: string;
      /**
       *
       * @example "GET"
       */
      method?: string;
      /**
       * Array of request headers

       * @example ["content-type: xxx","header2: val2"]
       */
      headers?: string[];
      /**
       *
       * @example "<html><body><h1>Hello World!</h1></body></html>"
       */
      body?: string;
      /**
       * If `dumpIframe` is activated, this property contains iframe HTML.

       * @example "<html><body><h1>Iframe content</h1></body></html>"
       */
      bodyIframe?: string;
      /**
       *
       * @example 200
       */
      status?: number;
      /**
       * Object with response headers

       * @example {"content-type":"application/json"}
       */
      responseHeaders?: { [key: string]: unknown };
    };
    /**
     *
     * @example ["content-type: xxx","header2: val2"]
     */
    headers: string[];
  };
  /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
  body?: string;
}> {
  const _resp = await sdkRequest<{
    info?: {
      /**
       *
       * @example 200
       */
      statusCode: number;
      /**
       *
       * @example "https://example.com/url"
       */
      finalUrl: string;
      catchedAjax?: {
        /**
         *
         * @example "https://example.com/api/data.json"
         */
        url?: string;
        /**
         *
         * @example "GET"
         */
        method?: string;
        /**
       * Array of request headers

       * @example ["content-type: xxx","header2: val2"]
       */
        headers?: string[];
        /**
         *
         * @example "<html><body><h1>Hello World!</h1></body></html>"
         */
        body?: string;
        /**
       * If `dumpIframe` is activated, this property contains iframe HTML.

       * @example "<html><body><h1>Iframe content</h1></body></html>"
       */
        bodyIframe?: string;
        /**
         *
         * @example 200
         */
        status?: number;
        /**
       * Object with response headers

       * @example {"content-type":"application/json"}
       */
        responseHeaders?: { [key: string]: unknown };
      };
      /**
       *
       * @example ["content-type: xxx","header2: val2"]
       */
      headers: string[];
    };
    /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
    body?: string;
  }>({
    method: "POST",
    path: `/v2/scrape-js`,
    operationId: "scrapeJsV2",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      url,
      waitForSelector,
      postWaitTime,
      headers,
      retryNum,
      geo,
      proxy,
      timeout,
      textNotExpected,
      statusNotExpected,
      blockImages,
      blockMedia,
      screenshot,
      extractor,
    },
    config,
  });
  return _resp.data;
}

export class ScrapeJsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Scrapes a URL with a real Chrome browser engine to render JavaScript-dependent pages. Use this endpoint when `/scrape` does not retrieve the required page content; set `waitForSelector` or `postWaitTime` when you need to control when page loading is considered complete. The response includes the rendered HTML and browser metadata.
   *
   * Launches real Chrome browser engine, use only when /scrape endpoint features are not enough.
   */
  scrapeJs(params: ScrapeJsParams, requestOptions?: RequestOptions): ReturnType<typeof scrapeJs> {
    return scrapeJs(this._config, params, requestOptions);
  }
  /**
   * Scrapes a URL with the newer real Chrome browser engine to render JavaScript-dependent pages. Use this endpoint when browser rendering is required, including for sites protected by services such as Cloudflare, Datadome, Kasada, or PerimeterX. Access is available only through APIRoad.
   *
   * Launches real Chrome browser engine, better success rate for websites protected by Cloudflare, Datadome, Kasada, PermimeterX. ATTENTION: Only available via APIRoad!
   */
  v2(params: ScrapeJsV2Params, requestOptions?: RequestOptions): ReturnType<typeof scrapeJsV2> {
    return scrapeJsV2(this._config, params, requestOptions);
  }
}
