// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { ScrapeNamespace } from "./methods/scrape";
import { ScrapeJsNamespace } from "./methods/scrapeJs";

export class ScrapeNinjaWebScraping {
  private readonly _config: ClientConfig;
  readonly scrape: ScrapeNamespace;
  readonly scrapeJs: ScrapeJsNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.scrape = new ScrapeNamespace(config);
    this.scrapeJs = new ScrapeJsNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
