// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export interface ScrapeParams {
  url: string;
  headers?: string[];
  retryNum?: number;
  geo?: string;
  proxy?: string;
  followRedirects?: number;
  timeout?: number;
  textNotExpected?: string[];
  statusNotExpected?: number[];
  extractor?: string;
}

/**
 * Scrapes a URL using Chrome browser TLS fingerprinting without executing JavaScript. Use this endpoint for pages that do not require client-side rendering, and set `headers`, `geo`, or `proxy` to customize the request. The response includes the HTML body and request metadata.
 *
 * Use high-performance web scraping endpoint with Chrome browser TLS fingerprint, but without JavaScript execution and real browser overhead.
 *
 * @param url - URL to scrape
 * @param headers - Custom headers to send with the request. By default, regular
 *   Chrome browser headers are sent to the target URL.
 * @param retryNum - Amount of attempts.
 * @param geo - Geo location for basic proxy pools (you can purchase premium
 *   ScrapeNinja proxies for wider country selection and higher proxy quality).
 *   [Read more about ScrapeNinja proxy
 *   setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param proxy - Premium or your own proxy URL (overrides `geo` field). [Read
 *   more about ScrapeNinja proxy setup](https://scrapeninja.net/docs/proxy-setup/)
 * @param followRedirects - Follow redirects.
 * @param timeout - Timeout per attempt, in seconds. Each retry will take
 *   [timeout] number of seconds.
 * @param textNotExpected - Text which will trigger a retry from another proxy
 *   address.
 * @param statusNotExpected - HTTP response statuses which will trigger a retry
 *   from another proxy address.
 * @param extractor - Custom JS function to extract JSON values from scraped
 *   HTML. Write&test your own extractor on
 *   https://scrapeninja.net/cheerio-sandbox/
 */
export async function scrape(
  config: ClientConfig,
  {
    url,
    headers,
    retryNum,
    geo,
    proxy,
    followRedirects,
    timeout,
    textNotExpected,
    statusNotExpected,
    extractor,
  }: ScrapeParams,
  requestOptions?: RequestOptions,
): Promise<{
  info?: {
    /**
     *
     * @example 200
     */
    statusCode: number;
    /**
     *
     * @example "https://example.com/url"
     */
    finalUrl: string;
    /**
     *
     * @example ["content-type: xxx","header2: val2"]
     */
    headers: string[];
  };
  /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
  body?: string;
}> {
  const _resp = await sdkRequest<{
    info?: {
      /**
       *
       * @example 200
       */
      statusCode: number;
      /**
       *
       * @example "https://example.com/url"
       */
      finalUrl: string;
      /**
       *
       * @example ["content-type: xxx","header2: val2"]
       */
      headers: string[];
    };
    /**
   * HTML body of the rendered page.

   * @example "<html><body><h1>Hello World!</h1></body></html>"
   */
    body?: string;
  }>({
    method: "POST",
    path: `/scrape`,
    operationId: "scrape",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      url,
      headers,
      retryNum,
      geo,
      proxy,
      followRedirects,
      timeout,
      textNotExpected,
      statusNotExpected,
      extractor,
    },
    config,
  });
  return _resp.data;
}

export class ScrapeNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Scrapes a URL using Chrome browser TLS fingerprinting without executing JavaScript. Use this endpoint for pages that do not require client-side rendering, and set `headers`, `geo`, or `proxy` to customize the request. The response includes the HTML body and request metadata.
   *
   * Use high-performance web scraping endpoint with Chrome browser TLS fingerprint, but without JavaScript execution and real browser overhead.
   */
  scrape(params: ScrapeParams, requestOptions?: RequestOptions): ReturnType<typeof scrape> {
    return scrape(this._config, params, requestOptions);
  }
}
